services:
  backend:
    image: sastrebocalonmaxi/backend3:1.2
    container_name: backend-iii
    ports:
      - "3000:3000"    
    depends_on:
      - mongo
    env_file:
      - .env.prod
    command: ["node", "src/app.js"]
    restart: always

  mongo:
    image: mongo:6.0
    container_name: mongodb-iii
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

volumes:
  mongo_data:
