const EErrors = {
    INVALID_PARAM: 'INVALID_PARAM',
    INCOMPLETE_DATA: 'INCOMPLETE_DATA',
    NOT_FOUND: 'NOT_FOUND',
    DATABASE_ERROR: 'DATABASE_ERROR',
    UNAUTHORIZED: 'UNAUTHORIZED'
};

export default EErrors;